services:
  evolution-api:
    image: evoapicloud/evolution-api:latest
    ports:
      - "3232:8080"
    environment:
      - SERVER_URL=http://${{RAILWAY_PUBLIC_DOMAIN}}
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=TlakaniSuperSecreto2026
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://neondb_owner:npg_O0ENASyW2zvB@ep-lucky-sky-b4nxrzyc-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - CACHE_REDIS_ENABLED=false
      - CACHE_REDIS_URI=redis://redis-db:6379/1
    depends_on:
      - postgres-db
      - redis-db

  postgres-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=evolution_db
    ports:
      - "5433:5432"

  redis-db:
    image: redis:alpine
    ports:
      - "6379:6379"
